# This .travis.yml is modified from the sample at
# https://docs.haskellstack.org/en/stable/travis_ci/

# We don't use a specific language with stack
language: generic

# Use new container infrastructure to enable caching
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.stack
  - $HOME/build/davnn/curiousobserver/.stack-work

# Download and unpack the stack executable
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait 60 stack setup --no-terminal
# Disable concurrent jobs to prevent out of memory
# See: https://serokell.io/posts/ru/2018-01-24-using-travis-CI-for-Haskell-projects.html
  - travis_wait 60 stack build --stack-yaml stack_ci.yaml --fast --jobs 2 --no-terminal --no-haddock-deps

script:
- stack exec curiousobserver build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
