name:                fastpaced
version:             0.1.0.0
github:              "davnn/fastpaced"
license:             BSD3
author:              "David Muhr"
maintainer:          "muhrdavid+git@gmail.com"
copyright:           "David Muhr"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/davnn/fastpaced#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll
- pandoc
- filepath

executables:
  fastpaced:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
