# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-10.5

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- hakyll-sass-0.2.3

flags:
  # Needed for macOS
  # See: https://github.com/jakubfijalkowski/hlibsass
  hlibsass:
    externalLibsass: true
